version: '2.4'
# version 2.x allows you to use depends_on with conditions that cause
# the node app to wait on mongo to respond to a healthy healthcheck before node is started
# v3.x doesn't have this feature yet, and is only needed if you want to use Swarm

services:

  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - '80:80'
  web:
    image: httpd
    volumes:
      - ./front_v0.1/html:/usr/local/apache2/htdocs/
  backendv0:
    build: 
      context: ./back_v01/
      dockerfile: Dockerfile

    
