version: '2.4'
# version 2.x allows you to use depends_on with conditions that cause
# the node app to wait on mongo to respond to a healthy healthcheck before node is started
# v3.x doesn't have this feature yet, and is only needed if you want to use Swarm

services:

  proxy:
    image: nginx-proxy
    build:
      context: .
      dockerfile: nginx.Dockerfile
    #   dockerfile: nginx:alpine
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./front_v0.2/index.html:/usr/share/nginx/html/index.html
      # - ./front_v0.2/index.html:/home/index.html
    ports:
      - '80:80'
      - '8080:8080'
      - '3000:3000'
  web:
    image: httpd
    volumes:
      - ./front_v0.1/html:/usr/local/apache2/htdocs/
  backendv0:
    image: node-back:latest
    build:
      context: ./back_v0.1/
      dockerfile: Dockerfile
    # ports:
    #   - 3000:3000
