version: '2.4'
# version 2.x allows you to use depends_on with conditions that cause
# the node app to wait on mongo to respond to a healthy healthcheck before node is started
# v3.x doesn't have this feature yet, and is only needed if you want to use Swarm

services:

  proxy:
    image: nginx-proxy
    build:
      context: .
      dockerfile: nginx.Dockerfile
    #   dockerfile: nginx:alpine
    volumes:
      # - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./front_v0.2/index.html:/usr/share/nginx/html/index.html
      # - ./data/index.html:/usr/share/nginx/html/index.html
      - ./front_v0.2/index.html:/data/www/index.html
      - ./data/:/data/
      # - ./front_v0.2/index.html:/home/index.html
    ports:
      - '82:82'
      # # - '8080:8080'
      # - '8081:8081'
      - '3000:3000'
      - '2000:2000'
      - '3002:3002'
  web:
    image: httpd
    volumes:
      - ./front_v0.1/html:/usr/local/apache2/htdocs/
    # ports:
    #   - '8080:8080'
  backendv0:
    image: node-back:latest
    build:
      context: ./back_v0.1/
      dockerfile: Dockerfile
    volumes:
      - ./back_v0.1/app.js:/opt/node_app/app/app.js
    # ports:
    #   - 3000:3000
  next-app:
    image: next-app:latest
    build:
      context: ./front_v1.2/salesfloor/next-app
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./front_v1.2/salesfloor/next-app/src:/app/src
      - ./front_v1.2/salesfloor/next-app/public:/app/public
